//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace LibraryApp.service21.xsd {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ProjectLibraryService")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime BirthDateField;
        
        private string IdnpField;
        
        private string NameField;
        
        private string SurnameField;
        
        private int UserIdField;
        
        private byte[] UserPicField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idnp {
            get {
                return this.IdnpField;
            }
            set {
                if ((object.ReferenceEquals(this.IdnpField, value) != true)) {
                    this.IdnpField = value;
                    this.RaisePropertyChanged("Idnp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] UserPic {
            get {
                return this.UserPicField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPicField, value) != true)) {
                    this.UserPicField = value;
                    this.RaisePropertyChanged("UserPic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/ProjectLibraryService")]
    public partial class Book : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AmountField;
        
        private string AuthorField;
        
        private int BookIdField;
        
        private bool CanLendField;
        
        private string CategoryField;
        
        private LibraryApp.service21.xsd.Rmf CollectionField;
        
        private string CollectionIdField;
        
        private string DescriptionField;
        
        private byte[] ImageField;
        
        private decimal PriceField;
        
        private string PublisherField;
        
        private System.DateTime RegistrationDateField;
        
        private string TitleField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanLend {
            get {
                return this.CanLendField;
            }
            set {
                if ((this.CanLendField.Equals(value) != true)) {
                    this.CanLendField = value;
                    this.RaisePropertyChanged("CanLend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibraryApp.service21.xsd.Rmf Collection {
            get {
                return this.CollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionField, value) != true)) {
                    this.CollectionField = value;
                    this.RaisePropertyChanged("Collection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionId {
            get {
                return this.CollectionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionIdField, value) != true)) {
                    this.CollectionIdField = value;
                    this.RaisePropertyChanged("CollectionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservedBook", Namespace="http://schemas.datacontract.org/2004/07/ProjectLibraryService")]
    public partial class ReservedBook : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LibraryApp.service21.xsd.BookCode BookCodeField;
        
        private int CodeField;
        
        private int ReservationIdField;
        
        private System.DateTime TimeOutField;
        
        private LibraryApp.service21.xsd.User UserField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibraryApp.service21.xsd.BookCode BookCode {
            get {
                return this.BookCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BookCodeField, value) != true)) {
                    this.BookCodeField = value;
                    this.RaisePropertyChanged("BookCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationId {
            get {
                return this.ReservationIdField;
            }
            set {
                if ((this.ReservationIdField.Equals(value) != true)) {
                    this.ReservationIdField = value;
                    this.RaisePropertyChanged("ReservationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeOut {
            get {
                return this.TimeOutField;
            }
            set {
                if ((this.TimeOutField.Equals(value) != true)) {
                    this.TimeOutField = value;
                    this.RaisePropertyChanged("TimeOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibraryApp.service21.xsd.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rmf", Namespace="http://schemas.datacontract.org/2004/07/ProjectLibraryService")]
    public partial class Rmf : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ContentCatField;
        
        private System.DateTime DateInField;
        
        private System.Nullable<System.DateTime> DateOutField;
        
        private string DocIdField;
        
        private byte[] DocImgField;
        
        private int FirstInvNrField;
        
        private string IdRmfField;
        
        private System.Nullable<bool> IsOutField;
        
        private int LastInvNrField;
        
        private string OriginField;
        
        private string OutCauseField;
        
        private int QuantityField;
        
        private System.Nullable<decimal> TotalValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentCat {
            get {
                return this.ContentCatField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentCatField, value) != true)) {
                    this.ContentCatField = value;
                    this.RaisePropertyChanged("ContentCat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateIn {
            get {
                return this.DateInField;
            }
            set {
                if ((this.DateInField.Equals(value) != true)) {
                    this.DateInField = value;
                    this.RaisePropertyChanged("DateIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOut {
            get {
                return this.DateOutField;
            }
            set {
                if ((this.DateOutField.Equals(value) != true)) {
                    this.DateOutField = value;
                    this.RaisePropertyChanged("DateOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocId {
            get {
                return this.DocIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIdField, value) != true)) {
                    this.DocIdField = value;
                    this.RaisePropertyChanged("DocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocImg {
            get {
                return this.DocImgField;
            }
            set {
                if ((object.ReferenceEquals(this.DocImgField, value) != true)) {
                    this.DocImgField = value;
                    this.RaisePropertyChanged("DocImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstInvNr {
            get {
                return this.FirstInvNrField;
            }
            set {
                if ((this.FirstInvNrField.Equals(value) != true)) {
                    this.FirstInvNrField = value;
                    this.RaisePropertyChanged("FirstInvNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRmf {
            get {
                return this.IdRmfField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRmfField, value) != true)) {
                    this.IdRmfField = value;
                    this.RaisePropertyChanged("IdRmf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsOut {
            get {
                return this.IsOutField;
            }
            set {
                if ((this.IsOutField.Equals(value) != true)) {
                    this.IsOutField = value;
                    this.RaisePropertyChanged("IsOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastInvNr {
            get {
                return this.LastInvNrField;
            }
            set {
                if ((this.LastInvNrField.Equals(value) != true)) {
                    this.LastInvNrField = value;
                    this.RaisePropertyChanged("LastInvNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutCause {
            get {
                return this.OutCauseField;
            }
            set {
                if ((object.ReferenceEquals(this.OutCauseField, value) != true)) {
                    this.OutCauseField = value;
                    this.RaisePropertyChanged("OutCause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalValue {
            get {
                return this.TotalValueField;
            }
            set {
                if ((this.TotalValueField.Equals(value) != true)) {
                    this.TotalValueField = value;
                    this.RaisePropertyChanged("TotalValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookCode", Namespace="http://schemas.datacontract.org/2004/07/ProjectLibraryService")]
    public partial class BookCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LibraryApp.service21.xsd.Book BookField;
        
        private int BookIdField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibraryApp.service21.xsd.Book Book {
            get {
                return this.BookField;
            }
            set {
                if ((object.ReferenceEquals(this.BookField, value) != true)) {
                    this.BookField = value;
                    this.RaisePropertyChanged("Book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookCodeOwned", Namespace="http://schemas.datacontract.org/2004/07/ProjectLibraryService")]
    public partial class BookCodeOwned : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LibraryApp.service21.xsd.BookCode BookCodeField;
        
        private int CodeField;
        
        private int IdField;
        
        private System.DateTime LendDateField;
        
        private System.DateTime ReturnDateField;
        
        private LibraryApp.service21.xsd.User UserField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibraryApp.service21.xsd.BookCode BookCode {
            get {
                return this.BookCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BookCodeField, value) != true)) {
                    this.BookCodeField = value;
                    this.RaisePropertyChanged("BookCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LendDate {
            get {
                return this.LendDateField;
            }
            set {
                if ((this.LendDateField.Equals(value) != true)) {
                    this.LendDateField = value;
                    this.RaisePropertyChanged("LendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibraryApp.service21.xsd.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="service21.xsd.ISubServiceLayer")]
    public interface ISubServiceLayer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetUser", ReplyAction="http://tempuri.org/ISubServiceLayer/GetUserResponse")]
        System.Threading.Tasks.Task<LibraryApp.service21.xsd.User> GetUserAsync(string idnp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/CanLogIn", ReplyAction="http://tempuri.org/ISubServiceLayer/CanLogInResponse")]
        System.Threading.Tasks.Task<bool> CanLogInAsync(string name, string idnp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetUserImage", ReplyAction="http://tempuri.org/ISubServiceLayer/GetUserImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetUserImageAsync(string idnp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetUserBooksOnHandsCount", ReplyAction="http://tempuri.org/ISubServiceLayer/GetUserBooksOnHandsCountResponse")]
        System.Threading.Tasks.Task<int> GetUserBooksOnHandsCountAsync(LibraryApp.service21.xsd.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetUserBook", ReplyAction="http://tempuri.org/ISubServiceLayer/GetUserBookResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, LibraryApp.service21.xsd.Book>> GetUserBookAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetUserReservedBooks", ReplyAction="http://tempuri.org/ISubServiceLayer/GetUserReservedBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.ReservedBook>> GetUserReservedBooksAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetBooksCategories", ReplyAction="http://tempuri.org/ISubServiceLayer/GetBooksCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> GetBooksCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetBooksByCategory", ReplyAction="http://tempuri.org/ISubServiceLayer/GetBooksByCategoryResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> GetBooksByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetAvailableCount", ReplyAction="http://tempuri.org/ISubServiceLayer/GetAvailableCountResponse")]
        System.Threading.Tasks.Task<int> GetAvailableCountAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetBookById", ReplyAction="http://tempuri.org/ISubServiceLayer/GetBookByIdResponse")]
        System.Threading.Tasks.Task<LibraryApp.service21.xsd.Book> GetBookByIdAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/HasReserved", ReplyAction="http://tempuri.org/ISubServiceLayer/HasReservedResponse")]
        System.Threading.Tasks.Task<bool> HasReservedAsync(int userId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/HasOnHands", ReplyAction="http://tempuri.org/ISubServiceLayer/HasOnHandsResponse")]
        System.Threading.Tasks.Task<bool> HasOnHandsAsync(int userId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/AddReservation", ReplyAction="http://tempuri.org/ISubServiceLayer/AddReservationResponse")]
        System.Threading.Tasks.Task AddReservationAsync(int userId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/SearchBooks", ReplyAction="http://tempuri.org/ISubServiceLayer/SearchBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> SearchBooksAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetUserPreviouslyOwnedBooks", ReplyAction="http://tempuri.org/ISubServiceLayer/GetUserPreviouslyOwnedBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.BookCodeOwned>> GetUserPreviouslyOwnedBooksAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetNewestBooks", ReplyAction="http://tempuri.org/ISubServiceLayer/GetNewestBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> GetNewestBooksAsync(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubServiceLayer/GetRecommendedBooks", ReplyAction="http://tempuri.org/ISubServiceLayer/GetRecommendedBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> GetRecommendedBooksAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubServiceLayerChannel : LibraryApp.service21.xsd.ISubServiceLayer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubServiceLayerClient : System.ServiceModel.ClientBase<LibraryApp.service21.xsd.ISubServiceLayer>, LibraryApp.service21.xsd.ISubServiceLayer {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SubServiceLayerClient() : 
                base(SubServiceLayerClient.GetDefaultBinding(), SubServiceLayerClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISubServiceLayer.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubServiceLayerClient(EndpointConfiguration endpointConfiguration) : 
                base(SubServiceLayerClient.GetBindingForEndpoint(endpointConfiguration), SubServiceLayerClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubServiceLayerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SubServiceLayerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubServiceLayerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SubServiceLayerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubServiceLayerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<LibraryApp.service21.xsd.User> GetUserAsync(string idnp) {
            return base.Channel.GetUserAsync(idnp);
        }
        
        public System.Threading.Tasks.Task<bool> CanLogInAsync(string name, string idnp) {
            return base.Channel.CanLogInAsync(name, idnp);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetUserImageAsync(string idnp) {
            return base.Channel.GetUserImageAsync(idnp);
        }
        
        public System.Threading.Tasks.Task<int> GetUserBooksOnHandsCountAsync(LibraryApp.service21.xsd.User user) {
            return base.Channel.GetUserBooksOnHandsCountAsync(user);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, LibraryApp.service21.xsd.Book>> GetUserBookAsync(int userId) {
            return base.Channel.GetUserBookAsync(userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.ReservedBook>> GetUserReservedBooksAsync(int userId) {
            return base.Channel.GetUserReservedBooksAsync(userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> GetBooksCategoriesAsync() {
            return base.Channel.GetBooksCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> GetBooksByCategoryAsync(string category) {
            return base.Channel.GetBooksByCategoryAsync(category);
        }
        
        public System.Threading.Tasks.Task<int> GetAvailableCountAsync(int bookId) {
            return base.Channel.GetAvailableCountAsync(bookId);
        }
        
        public System.Threading.Tasks.Task<LibraryApp.service21.xsd.Book> GetBookByIdAsync(int bookId) {
            return base.Channel.GetBookByIdAsync(bookId);
        }
        
        public System.Threading.Tasks.Task<bool> HasReservedAsync(int userId, int bookId) {
            return base.Channel.HasReservedAsync(userId, bookId);
        }
        
        public System.Threading.Tasks.Task<bool> HasOnHandsAsync(int userId, int bookId) {
            return base.Channel.HasOnHandsAsync(userId, bookId);
        }
        
        public System.Threading.Tasks.Task AddReservationAsync(int userId, int bookId) {
            return base.Channel.AddReservationAsync(userId, bookId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> SearchBooksAsync(string searchString) {
            return base.Channel.SearchBooksAsync(searchString);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.BookCodeOwned>> GetUserPreviouslyOwnedBooksAsync(int userId) {
            return base.Channel.GetUserPreviouslyOwnedBooksAsync(userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> GetNewestBooksAsync(int count) {
            return base.Channel.GetNewestBooksAsync(count);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<LibraryApp.service21.xsd.Book>> GetRecommendedBooksAsync(int userId) {
            return base.Channel.GetRecommendedBooksAsync(userId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISubServiceLayer)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISubServiceLayer)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/ProjectLibraryService/SubServiceLayer" +
                        "/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return SubServiceLayerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISubServiceLayer);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return SubServiceLayerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISubServiceLayer);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ISubServiceLayer,
        }
    }
}
